apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: spring-petclinic
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        ports:
        - containerPort: 8080
          name: http

---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: spring-petclinic    
