apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: jammy-base
spec:
  buildImage:
    image: paketobuildpacks/build-jammy-base:0.1.115
  id: io.buildpacks.stacks.jammy
  runImage:
    image: paketobuildpacks/run-jammy-base:0.1.115
