# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build source code to container image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/setup-kubectl@v3
        name: Setup kubectl
      - name: Setup kubelogin
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.26'
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.RESOURCE_GROUP }}'
          cluster-name: '${{ secrets.CLUSTER_NAME }}'
          admin: 'false'
          use-kubelogin: 'true'
      - name: install kp
        run: |
          curl -L https://github.com/buildpacks-community/kpack-cli/releases/download/v0.13.0/kp-linux-amd64-0.13.0 -o kp
          chmod +x kp
      - name: Upload source code and build image
        run: ./kp image save spring-petclinic-image --tag ${{ secrets.ACR_LOGIN_SERVER }}/app/spring-petclinic:${{ github.sha }} --git ${{ github.repository }} --git-revision ${{ github.sha }} --builder my-builder --service-account tutorial-service-account
      - name: Stream build logs
        run: ./kp build logs spring-petclinic-image -b 1
