# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build source code to container image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
      - name: Login to Kubernetes cluster
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          kubectl config use-context liyi-build-svc-test-admin
      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
      - name: install kp
        run: |
          curl -L https://github.com/buildpacks-community/kpack-cli/releases/download/v0.13.0/kp-linux-amd64-0.13.0 -o kp
          chmod +x kp
      - name: Upload source code and build image
        run: ./kp image save spring-petclinic-image --tag ${{ secrets.ACR_PASSWORD }}/app/spring-petclinic --local-path . --builder my-builder --service-account tutorial-service-account
      - name: Stream build logs
        run: ./kp build logs spring-petclinic-image -b 1
