# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Scan Image

on:
  workflow_dispatch:
    inputs:
      imageDigest:
        description: 'Image Digest'
        required: true
        default: ''

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_REPO }}@${{ github.event.inputs.imageDigest }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os'
          severity: 'CRITICAL,HIGH'
        env:
          TRIVY_USERNAME: ${{ secrets.ACR_USER_NAME }} 
          TRIVY_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      